from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QFile, QTextStream
from PyQt5.QtWidgets import QGridLayout

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class ComboBoxCOMPORT(QtWidgets.QComboBox):
    popupAboutToBeShown = QtCore.pyqtSignal()

    def showPopup(self):
        self.popupAboutToBeShown.emit()
        super(ComboBoxCOMPORT, self).showPopup()


class Ui_MainWindowadvanced(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(910, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabbar = TabBar(self)
        self.tabWidget.setTabBar(self.tabbar)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabsClosable(False)
        # **************first tabwidget ******************/
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("Home")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.info)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(324, 430, 131, 41))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_logout = QtWidgets.QPushButton(self.info)
        self.pushButton_logout.setGeometry(QtCore.QRect(488, 430, 131, 41))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButtonconnect = QtWidgets.QPushButton(self.info)
        self.pushButtonconnect.setGeometry(QtCore.QRect(160, 430, 131, 41))
        self.pushButtonconnect.setObjectName("pushButtonconnect")
        self.comboBox_serial = ComboBoxCOMPORT(self.info)
        self.comboBox_serial.setGeometry(QtCore.QRect(250, 330, 365, 22))
        self.comboBox_serial.setObjectName("comboBox_serial")
        self.label_7 = QtWidgets.QLabel(self.info)
        self.label_7.setGeometry(QtCore.QRect(162, 367, 61, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_baud = QtWidgets.QComboBox(self.info)
        self.comboBox_baud.setGeometry(QtCore.QRect(250, 367, 365, 22))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.label_6 = QtWidgets.QLabel(self.info)
        self.label_6.setGeometry(QtCore.QRect(160, 330, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.info)
        self.label_8.setGeometry(QtCore.QRect(320, 250, 451, 21))
        self.label_8.setObjectName("label_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.info)
        self.graphicsView.setGeometry(QtCore.QRect(160, 20, 456, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.setStyleSheet("border: 0px")
        self.tabWidget.addTab(self.info, "")
        # ******************second tab widget***********************
        self.optab = QtWidgets.QWidget()
        self.optab.setObjectName("optab")
        self.plainTextEditadvanced = QtWidgets.QPlainTextEdit(self.optab)
        self.plainTextEditadvanced.setGeometry(QtCore.QRect(425, 10, 371, 511))
        self.plainTextEditadvanced.setObjectName("plainTextEditadvanced")
        self.pushButtoncollapsexpand = QtWidgets.QPushButton(self.optab)
        self.pushButtoncollapsexpand.setGeometry(QtCore.QRect(797, 10, 12, 511))
        self.pushButtoncollapsexpand.setObjectName("pushButtoncollapsexpand")
        self.groupBox = QtWidgets.QGroupBox(self.optab)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 381, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_verifyflash = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_verifyflash.setGeometry(QtCore.QRect(20, 10, 200, 25))
        self.pushButton_verifyflash.setObjectName("pushButton_verifyflash")
        self.lineEdit_verifyoffset = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_verifyoffset.setGeometry(QtCore.QRect(250, 10, 111, 25))
        self.lineEdit_verifyoffset.setObjectName("lineEditreadmemaddr")
        self.pushButton_loadram = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_loadram.setGeometry(QtCore.QRect(20, 45, 160, 25))
        self.pushButton_loadram.setObjectName("pushButton_loadram")
        self.pushButton_chipid = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_chipid.setGeometry(QtCore.QRect(200, 45, 160, 25))
        self.pushButton_chipid.setObjectName("pushButton_chipid")
        self.groupBox_2 = QtWidgets.QGroupBox(self.optab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 140, 381, 161))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_imageinfo = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_imageinfo.setGeometry(QtCore.QRect(200, 100, 161, 25))
        self.pushButton_imageinfo.setObjectName("pushButton_imageinfo")
        self.pushButton_flashcombined = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_flashcombined.setGeometry(QtCore.QRect(20, 20, 161, 25))
        self.pushButton_flashcombined.setObjectName("pushButton_flashcombined")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 100, 161, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_flashAll = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_flashAll.setGeometry(QtCore.QRect(200, 20, 161, 25))
        self.pushButton_flashAll.setObjectName("pushButton_flashAll")
        self.pushButton_flashfirmware = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_flashfirmware.setGeometry(QtCore.QRect(20, 60, 161, 25))
        self.pushButton_flashfirmware.setObjectName("pushButton_flashfirmware")
        self.pushButton_eraseentireflash = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_eraseentireflash.setGeometry(QtCore.QRect(200, 60, 161, 25))
        self.pushButton_eraseentireflash.setObjectName("pushButton_eraseentireflash")
        self.groupBox_3 = QtWidgets.QGroupBox(self.optab)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 330, 381, 121))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_clearop = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clearop.setGeometry(QtCore.QRect(20, 20, 161, 25))
        self.pushButton_clearop.setObjectName("pushButton_clearop")
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_stop.setGeometry(QtCore.QRect(200, 20, 161, 25))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(20, 80, 340, 13))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.optab, "")
        # ********** third tabwidget*******************************
        self.Memo = QtWidgets.QWidget()
        self.Memo.setObjectName("Home")
        self.plainTextEditadvancedmem = QtWidgets.QPlainTextEdit(self.Memo)
        self.plainTextEditadvancedmem.setGeometry(QtCore.QRect(425, 10, 371, 511))
        self.plainTextEditadvancedmem.setObjectName("plainTextEditadvanced")
        self.pushButtoncollapsexpandm = QtWidgets.QPushButton(self.Memo)
        self.pushButtoncollapsexpandm.setGeometry(QtCore.QRect(797, 10, 12, 511))
        self.pushButtoncollapsexpandm.setObjectName("pushButtoncollapsexpandm")
        self.line = QtWidgets.QFrame(self.Memo)
        self.line.setGeometry(QtCore.QRect(420, 10, 10, 510))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBoxmemo = QtWidgets.QGroupBox(self.Memo)
        self.groupBoxmemo.setGeometry(QtCore.QRect(30, 10, 381, 400))
        self.groupBoxmemo.setTitle("")
        self.groupBoxmemo.setObjectName("groupBox")
        self.pushButton_eraseregion = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_eraseregion.setGeometry(QtCore.QRect(20, 110, 101, 25))
        self.pushButton_eraseregion.setObjectName("pushButton_eraseregion")
        self.lineEditreadmemaddr = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEditreadmemaddr.setGeometry(QtCore.QRect(250, 20, 111, 25))
        self.lineEditreadmemaddr.setObjectName("lineEditreadmemaddr")
        self.pushButton_readmem = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_readmem.setGeometry(QtCore.QRect(20, 20, 221, 25))
        self.pushButton_readmem.setObjectName("pushButton_readmem")
        self.lineEdit_writemem1 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_writemem1.setGeometry(QtCore.QRect(132, 70, 72, 25))
        self.lineEdit_writemem1.setObjectName("lineEdit_writemem1")
        self.lineEdit_writemem2 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_writemem2.setGeometry(QtCore.QRect(212, 70, 70, 25))
        self.lineEdit_writemem2.setObjectName("lineEdit_writemem2")
        self.lineEdit_writemem3 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_writemem3.setGeometry(QtCore.QRect(290, 70, 70, 25))
        self.lineEdit_writemem3.setObjectName("lineEdit_writemem3")
        self.lineEdit_eraseregion2 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_eraseregion2.setGeometry(QtCore.QRect(250, 111, 111, 25))
        self.lineEdit_eraseregion2.setObjectName("lineEdit_eraseregion2")
        self.lineEdit_eraseregion1 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_eraseregion1.setGeometry(QtCore.QRect(132, 111, 111, 25))
        self.lineEdit_eraseregion1.setObjectName("lineEdit_eraseregion1")
        self.pushButton_writemem = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_writemem.setGeometry(QtCore.QRect(20, 69, 101, 25))
        self.pushButton_writemem.setObjectName("pushButton_writemem")
        self.pushButton_dumpmem = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_dumpmem.setGeometry(QtCore.QRect(20, 150, 101, 25))
        self.pushButton_dumpmem.setObjectName("pushButton_dumpmem")
        self.lineEdit_dumpmem1 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_dumpmem1.setGeometry(QtCore.QRect(132, 150, 111, 25))
        self.lineEdit_dumpmem1.setObjectName("lineEdit_eraseregion2")
        self.lineEdit_dumpmem2 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_dumpmem2.setGeometry(QtCore.QRect(250, 150, 111, 25))
        self.lineEdit_dumpmem2.setObjectName("lineEdit_eraseregion1")
        self.pushButton_readFlash = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_readFlash.setGeometry(QtCore.QRect(20, 270, 101, 25))
        self.pushButton_readFlash.setObjectName("pushButton_readFlash")
        self.pushButton_Fusedump = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_Fusedump.setGeometry(QtCore.QRect(20, 310, 101, 25))
        self.pushButton_Fusedump.setObjectName("pushButton_Fusedump")
        self.pushButton_encrypt = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_encrypt.setGeometry(QtCore.QRect(132, 310, 101, 25))
        self.pushButton_encrypt.setObjectName("pushButton_encrypt")
        self.lineEdit_readFlash1 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_readFlash1.setGeometry(QtCore.QRect(132, 270, 111, 25))
        self.lineEdit_readFlash1.setObjectName("lineEdit_readFlash1")
        self.lineEdit_readFlash2 = QtWidgets.QLineEdit(self.groupBoxmemo)
        self.lineEdit_readFlash2.setGeometry(QtCore.QRect(250, 270, 111, 25))
        self.lineEdit_readFlash2.setObjectName("lineEdit_readFlash2")
        self.pushButton_readstatusreg = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_readstatusreg.setGeometry(QtCore.QRect(20, 190, 160, 25))
        self.pushButton_readstatusreg.setObjectName("pushButton_readstatusreg")
        self.comboBox_readstatusreg = QtWidgets.QComboBox(self.groupBoxmemo)
        self.comboBox_readstatusreg.setGeometry(QtCore.QRect(200, 190, 160, 25))
        self.comboBox_readstatusreg.setObjectName("comboBox_flashmode")
        self.pushButton_writestatusreg = QtWidgets.QPushButton(self.groupBoxmemo)
        self.pushButton_writestatusreg.setGeometry(QtCore.QRect(20, 230, 160, 25))
        self.pushButton_writestatusreg.setObjectName("pushButton_readstatusreg")
        self.comboBox_writestatusreg = QtWidgets.QComboBox(self.groupBoxmemo)
        self.comboBox_writestatusreg.setGeometry(QtCore.QRect(200, 230, 160, 25))
        self.comboBox_writestatusreg.setObjectName("comboBox_flashmode")
        self.groupBox_2memo = QtWidgets.QGroupBox(self.Memo)
        self.groupBox_2memo.setGeometry(QtCore.QRect(30, 421, 381, 100))
        self.groupBox_2memo.setTitle("")
        self.groupBox_2memo.setObjectName("groupBox_3")
        self.pushButton_clearmemo = QtWidgets.QPushButton(self.groupBox_2memo)
        self.pushButton_clearmemo.setGeometry(QtCore.QRect(20, 20, 161, 25))
        self.pushButton_clearmemo.setObjectName("pushButton_clearop")
        self.pushButton_stopmemo = QtWidgets.QPushButton(self.groupBox_2memo)
        self.pushButton_stopmemo.setGeometry(QtCore.QRect(200, 20, 161, 25))
        self.pushButton_stopmemo.setObjectName("pushButton_stop")
        self.progressBarmemo = QtWidgets.QProgressBar(self.groupBox_2memo)
        self.progressBarmemo.setGeometry(QtCore.QRect(20, 70, 340, 13))
        self.progressBarmemo.setProperty("value", 24)
        self.progressBarmemo.setObjectName("progressBar")
        self.tabWidget.addTab(self.Memo, "")
        # ****************fourth tabwidget******************************
        self.datatab = QtWidgets.QWidget()
        self.datatab.setObjectName("datatab")
        self.groupBox_data = QtWidgets.QGroupBox(self.datatab)
        self.groupBox_data.setGeometry(QtCore.QRect(40, 350, 705, 100))
        self.groupBox_data.setTitle("")
        self.groupBox_data.setObjectName("groupBox_data")
        self.pushButton_selectall = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_selectall.setGeometry(QtCore.QRect(10, 30, 120, 40))
        self.pushButton_selectall.setObjectName("pushButton_selectall")
        self.pushButton_cleardata = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_cleardata.setGeometry(QtCore.QRect(150, 30, 120, 40))
        self.pushButton_cleardata.setObjectName("pushButton_cleardata")
        self.pushButton_combine = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_combine.setGeometry(QtCore.QRect(290, 30, 120, 40))
        self.pushButton_combine.setObjectName("pushButton_combine")
        self.pushButton_generatebinfromelf = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_generatebinfromelf.setGeometry(QtCore.QRect(430, 30, 120, 40))
        self.pushButton_generatebinfromelf.setObjectName("pushButton_generatebinfromelf")
        self.pushButton_zipfiles = QtWidgets.QPushButton(self.groupBox_data)
        self.pushButton_zipfiles.setGeometry(QtCore.QRect(570, 30, 120, 40))
        self.pushButton_zipfiles.setObjectName("pushButton_zipfiles")
        self.lineEdit_offset3 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_offset3.setGeometry(QtCore.QRect(625, 90, 101, 20))
        self.lineEdit_offset3.setObjectName("lineEdit_offset3")
        self.lineEdit_offset2 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_offset2.setGeometry(QtCore.QRect(625, 60, 101, 20))
        self.lineEdit_offset2.setObjectName("lineEdit_offset2")
        self.lineEdit_offset1 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_offset1.setGeometry(QtCore.QRect(625, 30, 101, 20))
        self.lineEdit_offset1.setObjectName("lineEdit_offset1")
        self.lineEdit_path1 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_path1.setGeometry(QtCore.QRect(80, 30, 500, 20))
        self.lineEdit_path1.setObjectName("lineEdit_path1")
        self.lineEdit_path2 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_path2.setGeometry(QtCore.QRect(80, 60, 500, 20))
        self.lineEdit_path2.setObjectName("lineEdit_path2")
        self.lineEdit_path3 = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_path3.setGeometry(QtCore.QRect(80, 90, 500, 20))
        self.lineEdit_path3.setObjectName("lineEdit_path3")
        self.lineEdit_keypath = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_keypath.setGeometry(QtCore.QRect(80, 180, 500, 20))
        self.lineEdit_keypath.setObjectName("lineEdit_keypath")
        self.lineEdit_combinedfile = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_combinedfile.setGeometry(QtCore.QRect(80, 120, 500, 20))
        self.lineEdit_combinedfile.setObjectName("lineEdit_combinedfile")
        self.checkBox_3 = QtWidgets.QCheckBox(self.datatab)
        self.checkBox_3.setGeometry(QtCore.QRect(735, 90, 31, 21))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.datatab)
        self.checkBox_2.setGeometry(QtCore.QRect(735, 60, 31, 21))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.datatab)
        self.checkBox_1.setGeometry(QtCore.QRect(735, 30, 31, 21))
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.pushButton_path1 = QtWidgets.QPushButton(self.datatab)
        self.pushButton_path1.setGeometry(QtCore.QRect(40, 31, 31, 20))
        self.pushButton_path1.setObjectName("pushButton_path1")
        self.pushButton_path2 = QtWidgets.QPushButton(self.datatab)
        self.pushButton_path2.setGeometry(QtCore.QRect(40, 60, 31, 20))
        self.pushButton_path2.setObjectName("pushButton_path2")
        self.pushButton_path3 = QtWidgets.QPushButton(self.datatab)
        self.pushButton_path3.setGeometry(QtCore.QRect(40, 91, 31, 20))
        self.pushButton_path3.setObjectName("pushButton_path3")
        self.pushButton_pathkey = QtWidgets.QPushButton(self.datatab)
        self.pushButton_pathkey.setGeometry(QtCore.QRect(40, 180, 31, 20))
        self.pushButton_pathkey.setObjectName("pushButton_pathkey")
        self.lineEdit_elffile = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_elffile.setGeometry(QtCore.QRect(80, 150, 500, 20))
        self.lineEdit_elffile.setObjectName("lineEdit_elffile")
        self.pushButton_elffile = QtWidgets.QPushButton(self.datatab)
        self.pushButton_elffile.setGeometry(QtCore.QRect(40, 150, 31, 20))
        self.pushButton_elffile.setObjectName("pushButton_elffile")
        self.pushButton_browsecombined = QtWidgets.QPushButton(self.datatab)
        self.pushButton_browsecombined.setGeometry(QtCore.QRect(40, 120, 31, 20))
        self.pushButton_browsecombined.setObjectName("pushButton_browsecombined")
        self.lineEdit_offsetcombined = QtWidgets.QLineEdit(self.datatab)
        self.lineEdit_offsetcombined.setGeometry(QtCore.QRect(625, 120, 101, 20))
        self.lineEdit_offsetcombined.setObjectName("lineEdit_offsetcombined")
        self.pushButton_genkey = QtWidgets.QPushButton(self.datatab)
        self.pushButton_genkey.setGeometry(QtCore.QRect(625, 180, 101, 22))
        self.pushButton_genkey.setObjectName("pushButton_selectall")
        self.tabWidget.addTab(self.datatab, "")
        # ********************fifth tabwidget**********************************
        self.fusetab = QtWidgets.QWidget()
        self.fusetab.setObjectName("fusetab")

        self.pushButton_reloadfusetab = QtWidgets.QPushButton(self.fusetab)
        self.pushButton_reloadfusetab.setGeometry(QtCore.QRect(320, 200, 100, 100))
        self.pushButton_reloadfusetab.setObjectName("pushButton_reloadfusetab")
        self.pushButton_reloadfusetab.setStyleSheet(
            "background-image: url('icons/sync.png'); border: none;background-color :none")

        self.btnref = QtWidgets.QPushButton()
        self.btn1 = QtWidgets.QPushButton()
        self.btn2 = QtWidgets.QPushButton()
        self.btn3 = QtWidgets.QPushButton()
        self.btn4 = QtWidgets.QPushButton()
        self.btn5 = QtWidgets.QPushButton()
        self.btn6 = QtWidgets.QPushButton()
        self.btn7 = QtWidgets.QPushButton()
        self.btn8 = QtWidgets.QPushButton()
        self.btn9 = QtWidgets.QPushButton()
        self.btn10 = QtWidgets.QPushButton()
        self.btn11 = QtWidgets.QPushButton()
        self.btn12 = QtWidgets.QPushButton()
        self.btn13 = QtWidgets.QPushButton()
        self.btn14 = QtWidgets.QPushButton()
        self.btn15 = QtWidgets.QPushButton()
        self.btn16 = QtWidgets.QPushButton()
        self.btn17 = QtWidgets.QPushButton()
        self.btn18 = QtWidgets.QPushButton()
        self.btn19 = QtWidgets.QPushButton()
        self.btn20 = QtWidgets.QPushButton()
        self.btn21 = QtWidgets.QPushButton()
        self.btn22 = QtWidgets.QPushButton()
        self.btn23 = QtWidgets.QPushButton()
        self.btn24 = QtWidgets.QPushButton()
        self.btn25 = QtWidgets.QPushButton()
        self.btn26 = QtWidgets.QPushButton()
        self.btn27 = QtWidgets.QPushButton()
        self.btn28 = QtWidgets.QPushButton()
        self.btn29 = QtWidgets.QPushButton()
        self.btn30 = QtWidgets.QPushButton()
        self.btn31 = QtWidgets.QPushButton()
        self.btn32 = QtWidgets.QPushButton()
        self.btnexport = QtWidgets.QPushButton()

        self.tabWidget.addTab(self.fusetab, "")
        # ***************sixth tabwidget********************************
        self.settingtab = QtWidgets.QWidget()
        self.settingtab.setObjectName("settingtab")
        self.comboBox_flashmode = QtWidgets.QComboBox(self.settingtab)
        self.comboBox_flashmode.setGeometry(QtCore.QRect(160, 160, 311, 22))
        self.comboBox_flashmode.setObjectName("comboBox_flashmode")
        self.comboBox_flashsize = QtWidgets.QComboBox(self.settingtab)
        self.comboBox_flashsize.setGeometry(QtCore.QRect(160, 120, 311, 22))
        self.comboBox_flashsize.setObjectName("comboBox_flashsize")
        self.label_5 = QtWidgets.QLabel(self.settingtab)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.settingtab)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 81, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_chip = QtWidgets.QComboBox(self.settingtab)
        self.comboBox_chip.setGeometry(QtCore.QRect(160, 80, 311, 22))
        self.comboBox_chip.setObjectName("comboBox_chip")
        self.label = QtWidgets.QLabel(self.settingtab)
        self.label.setGeometry(QtCore.QRect(50, 160, 81, 21))
        self.label.setObjectName("label")
        self.pushButton_default = QtWidgets.QPushButton(self.settingtab)
        self.pushButton_default.setGeometry(QtCore.QRect(580, 80, 131, 41))
        self.pushButton_default.setObjectName("pushButton_default")
        self.pushButton_savesetting = QtWidgets.QPushButton(self.settingtab)
        self.pushButton_savesetting.setGeometry(QtCore.QRect(580, 140, 131, 41))
        self.pushButton_savesetting.setObjectName("pushButton_savesetting")
        self.pushButton_loadsetting = QtWidgets.QPushButton(self.settingtab)
        self.pushButton_loadsetting.setGeometry(QtCore.QRect(580, 200, 131, 41))
        self.pushButton_loadsetting.setObjectName("pushButton_loadsetting")
        self.tabWidget.addTab(self.settingtab, "")
        # ***********************sventh tabwidget*******************************
        self.infohelptab = QtWidgets.QWidget()
        self.infohelptab.setObjectName("infohelptab")
        self.layoutinfotab = QGridLayout()
        self.infohelptab.setLayout(self.layoutinfotab)
        self.textbrowser = QtWidgets.QTextBrowser()
        # self.infohelptab.setFrameStyle(QtWidgets.QFrame.NoFrame)
        self.textbrowser.setStyleSheet("border: none")
        self.layoutinfotab.addWidget(self.textbrowser)
        f = QFile("help.html")
        f.open(QFile.ReadOnly | QFile.Text)
        istream = QTextStream(f)
        self.textbrowser.setHtml(istream.readAll())
        f.close()


        self.tabWidget.addTab(self.infohelptab, "")
        # ***************************************************************
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("Dark")

        self.actionLight_Blue = QtWidgets.QAction(MainWindow)
        self.actionLight_Blue.setObjectName("Light Blue")

        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionProduction_Mode = QtWidgets.QAction(MainWindow)
        self.actionProduction_Mode.setObjectName("actionProduction_Mode")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionProduction_Mode)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionDark)

        self.menuView.addAction(self.actionLight_Blue)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MicroTool 1.0"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_logout.setText(_translate("MainWindow", "Log out"))
        self.pushButtonconnect.setText(_translate("MainWindow", "Connect"))
        self.label_6.setText(_translate("MainWindow", " Serial Port"))
        self.label_8.setText(_translate("MainWindow", ""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("MainWindow", ""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Memo), _translate("MainWindow", ""))
        self.pushButton_chipid.setText(_translate("MainWindow", "chip ID"))
        self.pushButton_zipfiles.setText(_translate("MainWindow", "Package"))
        self.pushButton_reloadfusetab.setText(_translate("MainWindow", ""))
        self.pushButton_eraseregion.setText(_translate("MainWindow", "Erase Region"))
        self.lineEditreadmemaddr.setPlaceholderText(_translate("MainWindow", "0x00000000 "))
        self.pushButton_readmem.setText(_translate("MainWindow", "Read Memory"))
        self.lineEdit_writemem2.setPlaceholderText(_translate("MainWindow", "0x00000000"))
        self.lineEdit_writemem1.setPlaceholderText(_translate("MainWindow", "0x00000000 "))
        self.lineEdit_eraseregion2.setPlaceholderText(_translate("MainWindow", "0x00000000"))
        self.lineEdit_eraseregion1.setPlaceholderText(_translate("MainWindow", "0x00000000 "))
        self.pushButton_writemem.setText(_translate("MainWindow", "Write Memory"))
        self.lineEdit_dumpmem1.setPlaceholderText(_translate("MainWindow", "0x00000000 "))
        self.lineEdit_dumpmem2.setPlaceholderText(_translate("MainWindow", "00000  "))
        self.pushButton_dumpmem.setText(_translate("MainWindow", "Dump Memory"))
        self.lineEdit_readFlash1.setPlaceholderText(_translate("MainWindow", "@ "))
        self.lineEdit_readFlash2.setPlaceholderText(_translate("MainWindow", "size  "))
        self.pushButton_readFlash.setText(_translate("MainWindow", "Read Flash"))
        self.pushButton_readstatusreg.setText(_translate("MainWindow", "Read Status Reg "))
        self.pushButton_imageinfo.setText(_translate("MainWindow", "Image Info"))
        self.pushButton_verifyflash.setText(_translate("MainWindow", "Verify Flash"))
        self.pushButton_flashcombined.setText(_translate("MainWindow", "Flash Combined"))
        self.pushButton_13.setText(_translate("MainWindow", "Flash Bootloader"))
        self.pushButton_flashfirmware.setText(_translate("MainWindow", "Flash firmware"))
        self.pushButton_eraseentireflash.setText(_translate("MainWindow", "Erase Entire Flash"))
        self.pushButton_clearop.setText(_translate("MainWindow", "Clear"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optab), _translate("MainWindow", ""))
        self.pushButton_selectall.setText(_translate("MainWindow", "Select All"))
        self.lineEdit_offset3.setPlaceholderText(_translate("MainWindow", "@"))
        self.lineEdit_offset1.setPlaceholderText(_translate("MainWindow", "@"))
        self.lineEdit_offset2.setPlaceholderText(_translate("MainWindow", "@"))
        self.lineEdit_offsetcombined.setPlaceholderText(_translate("MainWindow", "@"))
        self.lineEdit_combinedfile.setPlaceholderText(_translate("MainWindow", "Combined File"))
        self.lineEdit_path1.setPlaceholderText(_translate("MainWindow", "Firmware File"))
        self.lineEdit_path2.setPlaceholderText(_translate("MainWindow", "Bootloader File"))
        self.lineEdit_path3.setPlaceholderText(_translate("MainWindow", "Partition File"))
        self.lineEdit_keypath.setPlaceholderText(_translate("MainWindow", "Device Master Key Folder Path"))
        self.pushButton_browsecombined.setText(_translate("MainWindow", "..."))
        self.pushButton_cleardata.setText(_translate("MainWindow", "Clear"))
        self.pushButton_combine.setText(_translate("MainWindow", "Combine "))
        self.pushButton_path1.setText(_translate("MainWindow", "..."))
        self.pushButton_path2.setText(_translate("MainWindow", "..."))
        self.pushButton_path3.setText(_translate("MainWindow", "..."))
        self.pushButton_flashAll.setText(_translate("MainWindow", "Flash All"))
        self.pushButton_Fusedump.setText(_translate("MainWindow", "efuse dump"))
        self.pushButton_pathkey.setText(_translate("MainWindow", "..."))
        self.lineEdit_elffile.setPlaceholderText(_translate("MainWindow", "Browse elf  File"))
        self.pushButton_elffile.setText(_translate("MainWindow", "..."))
        self.pushButton_generatebinfromelf.setText(_translate("MainWindow", "Elf to Bin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.datatab), _translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", "Baud Rate"))
        self.label_5.setText(_translate("MainWindow", "Device"))
        self.label_2.setText(_translate("MainWindow", "Flash Size"))
        self.label.setText(_translate("MainWindow", "Flash Mode"))
        self.pushButton_default.setText(_translate("MainWindow", "Default"))
        self.pushButton_savesetting.setText(_translate("MainWindow", "Save Setting"))

        self.pushButton_loadsetting.setText(_translate("MainWindow", "Load  Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingtab), _translate("MainWindow", ""))
        self.pushButton_clearmemo.setText(_translate("MainWindow", "Clear"))
        self.pushButton_stopmemo.setText(_translate("MainWindow", "Stop"))
        self.pushButton_writestatusreg.setText(_translate("MainWindow", "Write Status Reg"))
        self.lineEdit_writemem3.setPlaceholderText(_translate("MainWindow", "0x00000000"))
        self.pushButton_encrypt.setText(_translate("MainWindow", "Encrypt Flash"))
        self.lineEdit_verifyoffset.setPlaceholderText(_translate("MainWindow", "0x00000000"))
        self.pushButton_loadram.setText(_translate("MainWindow", "Load RAM"))
        self.pushButton_genkey.setText(_translate("MainWindow", "Generate Key"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionLight_Blue.setText(_translate("MainWindow", "Light Blue"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionProduction_Mode.setText(_translate("MainWindow", "Production Mode"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


class TabBar(QtWidgets.QTabBar):

    def tabSizeHint(self, index):
        s = QtWidgets.QTabBar.tabSizeHint(self, index)
        s.transpose()
        return s

    def paintEvent(self, event):
        painter = QtWidgets.QStylePainter(self)
        opt = QtWidgets.QStyleOptionTab()

        for i in range(self.count()):
            self.initStyleOption(opt, i)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabShape, opt)
            painter.save()
            s = opt.rect.size()
            s.transpose()
            r = QtCore.QRect(QtCore.QPoint(), s)
            r.moveCenter(opt.rect.center())
            opt.rect = r
            c = self.tabRect(i).center()
            painter.translate(c)
            painter.rotate(90)
            painter.translate(-c)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabLabel, opt)
            painter.restore()
