# -*- mode: python -*-

block_cipher = None

a.datas += [
            ('./icons/checkbox.png', './icons/checkbox.png', 'DATA'),
            ('./icons/chip.png', './icons/chip.png', 'DATA'),
            ('./icons/collapse.png', './icons/collapse.png', 'DATA'),
            ('./icons/collapsev.png', './icons/collapsev.png', 'DATA'),
            ('./icons/connected.png', './icons/connected.png', 'DATA'),
            ('./icons/connection.png', './icons/connection.png', 'DATA'),
            ('./icons/deb.jpg', './icons/deb.jpg', 'DATA'),
            ('./icons/debug.png', './icons/debug.png', 'DATA'),
            ('./icons/disconnected.png', './icons/disconnected.png', 'DATA'),
            ('./icons/down_arrow.png', './icons/down_arrow.png', 'DATA'),
            ('./icons/espLogo.ico', './icons/espLogo.ico', 'DATA'),
            ('./icons/espLogo.png', './icons/espLogo.png', 'DATA'),
            ('./icons/Excel.png', './icons/Excel.png', 'DATA'),
            ('./icons/executefuse1.png', './icons/executefuse1.png', 'DATA'),
            ('./icons/expand.png', './icons/expand.png', 'DATA'),
            ('./icons/expandv.png', './icons/expandv.png', 'DATA'),
            ('./icons/fuse.png', './icons/fuse.png', 'DATA'),
            ('./icons/GREY-GEAR-LOADING.gif', './icons/GREY-GEAR-LOADING.gif', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/icon.png', './assets/icon.png', 'DATA'),
            ('./assets/settings.ini', './assets/settings.ini', 'DATA')
           ]



a = Analysis(['OpmodeMain.py'],
             pathex=['C:\\Users\\0xHunter\\Desktop\\Workspace\\PFE\\MicroTool'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='OpmodeMain',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
